### ISSUE TITLE
Please update uriparser to 0.9.0, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [OpenMandrivaAssociation/uriparser#3]
Hi!

Just a quick heads up that [uriparser 0.9.0](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.0) with security fixes has been released.

Thanks for updating!

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Any news?

**Comment by AngryPenguinPL** [comment]
Done.
Packages for Cooker and Lx 3 updated.

Thanks for reporting. Close as fixed.

**Comment by hartwork** [comment]
Thank you!
